### PR TITLE
add chainlist.json

### PR DESCRIPTION
**Pull request by supermassive**
Resolves https://github.com/brave/brave-browser/issues/23505

chainlist.json taken from https://chainid.network/chains.json

### CODE REVIEW

**Comment by supermassive** [comment]
@bbondy
Need to merge and upload to npm repo.
Will request security review when we update version for brave-core-crx-packager project.

**Comment by onyb** [comment]
Do you plan on addressing https://github.com/brave/brave-browser/issues/14574#issuecomment-1056299815 in this PR?

**Comment by supermassive** [comment]
> Do you plan on addressing [brave/brave-browser#14574 (comment)](https://github.com/brave/brave-browser/issues/14574#issuecomment-1056299815) in this PR?

Not sure now. Maybe it's better to handle here https://github.com/brave/brave-browser/issues/21399

**Comment by onyb** [comment]
@supermassive Please also bump the minor version number in `package.json` for auto-deployment by CI after the PR is merged.

**Review by kdenhartog — APPROVED** [review]
Seems good to me. One thing we should figure out is how to detect when this list updates so that we can pull in the latest updates (either manually or automated).

**Pull request merged**
